Document: debbie
Title: Debian debbie Manual
Author: <insert document author here>
Abstract: This manual describes what debbie is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/debbie/debbie.sgml.gz

Format: postscript
Files: /usr/share/doc/debbie/debbie.ps.gz

Format: text
Files: /usr/share/doc/debbie/debbie.text.gz

Format: HTML
Index: /usr/share/doc/debbie/html/index.html
Files: /usr/share/doc/debbie/html/*.html
